// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVvaJsmiaRWNL0l9az0X-km-uxaKHBXqY',
    appId: '1:455312617432:web:f3a3e95348026b11234cad',
    messagingSenderId: '455312617432',
    projectId: 'product-app-70634',
    authDomain: 'product-app-70634.firebaseapp.com',
    storageBucket: 'product-app-70634.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXghPCFn4bmPsJYHPW3NuGc8Jwsg_FoCY',
    appId: '1:455312617432:android:989d49bdcc99b754234cad',
    messagingSenderId: '455312617432',
    projectId: 'product-app-70634',
    storageBucket: 'product-app-70634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBObI2ilmU59rdM_SHFTCJ_2jOkRSxC4Lc',
    appId: '1:455312617432:ios:b970328b05650365234cad',
    messagingSenderId: '455312617432',
    projectId: 'product-app-70634',
    storageBucket: 'product-app-70634.appspot.com',
    iosBundleId: 'com.example.productApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVvaJsmiaRWNL0l9az0X-km-uxaKHBXqY',
    appId: '1:455312617432:web:9f7ae547a6363a2c234cad',
    messagingSenderId: '455312617432',
    projectId: 'product-app-70634',
    authDomain: 'product-app-70634.firebaseapp.com',
    storageBucket: 'product-app-70634.appspot.com',
  );
}
